spring.application.name=osManager-test

spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

jwt.secret=630bf2c7dd7b97cc4c120af79c7ec6ef637d8eec4ddbcda889024742ef1945c2
jwt.expiration=3600000

logging.level.root=WARN
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework=WARN

gemini.api-key=chave-dummy-para-testes
gemini.base-url=https://api.fake.gemini/generateContent

oci.config.path=~/.oci/config-dummy
oci.config.profile=DEFAULT_DUMMY
oci.vault.compartment-id=ocid1.compartment.oc1..dummycompartment
oci.vault.vault-id=ocid1.vault.oc1..dummyvault
oci.vault.encryption-key-id=ocid1.key.oc1..dummykey
