spring.application.name=osManager

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.url=jdbc:oracle:thin:@osmanager_medium
spring.datasource.hikari.data-source-properties.oracle.net.tns_admin=src/main/resources/wallet

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
