spring.application.name=osManager

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.url=jdbc:oracle:thin:@osmanager_medium
spring.datasource.hikari.data-source-properties.oracle.net.tns_admin=src/main/resources/wallet

spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

demandanet.base-url=https://assis.demandanet.com/smerp2010
demandanet.idescola=1047

oci.vault.compartment-id=${VAULT_COMPARTMENT_ID}
oci.vault.vault-id=${VAULT_ID}
oci.vault.encryption-key-id=${VAULT_ENCRYPTION_KEY_ID}
